### PR TITLE
remove duplicate testcases

### PR DESCRIPTION
**Pull request by sjaeckel**
while working on https://github.com/libtom/libtomcrypt/pull/319 I've realized that your collection contains a bunch of dupes which are removed here

### CODE REVIEW

**Comment by overheadhunter** [comment]
These test cases are generated by [this go program](https://github.com/cryptomator/siv-mode/blob/1.3.0/src/test/go/siv-test-vectors.go). Removing them for test efficiency is possible, of course. I am just wondering if it makes sense to dedup in the go program.

@timmclean You wrote it in the first place. Any thoughts on this?

**Comment by timmclean** [comment]
Yeah, it seems like it'd tidier to modify the test case generator to avoid producing the duplicates in the first place. It's a 40 KB improvement on 17 MB though, right?

**Comment by sjaeckel** [comment]
If I had searched a bit harder and found the generator myself I would've fixed it there as well :) 

IMO it can be left as it is now, because this testset is static ... and as soon as someone has the need to change it and touches the generator it'd probably make sense to fix it there...

**Comment by overheadhunter** [comment]
I'll reject this PR as discussed above. Thanks for thinking about providing your changes back upstream, anyway! ❤️

**Pull request closed without merging**
